version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Europe/Kiev
    open-pull-requests-limit: 10
    labels:
      - "🏠 Housekeeping"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "10:00"
      timezone: Europe/Kiev
    open-pull-requests-limit: 10
    labels:
      - "🏠 Housekeeping"
