require:
  - standard
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
